# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

name: Feries.ma
title: 
  ar: ØªÙ‚ÙˆÙŠÙ… Ø§Ù„Ø¹Ø·Ù„Ø§Øª Ø§Ù„Ø±Ø³Ù…ÙŠØ© Ù„Ø³Ù†ØªÙŠ 2024 / 2025 ÙÙŠ Ø§Ù„Ù…ØºØ±Ø¨
  en: Public holiday calendar for 2024 / 2025 in Morocco
  fr: Calendrier des jours fÃ©riÃ©s pour 2024 / 2025 au Maroc ğŸ‡²ğŸ‡¦
email: your-email@example.com
description: 
  ar: Ù‚Ø§Ù… Ù…ÙˆÙ‚Ø¹ Feries.ma Ø¨Ø¥Ø¹Ø¯Ø§Ø¯ Ù‚Ø§Ø¦Ù…Ø© ÙƒØ§Ù…Ù„Ø© Ù„Ù„Ø¹Ø·Ù„Ø§Øª Ø§Ù„Ø±Ø³Ù…ÙŠØ© ÙÙŠ Ø§Ù„Ù…ØºØ±Ø¨ Ù„Ø³Ù†Ø© 2024/2025.
  en: Feries.ma has drawn up the complete calendar of public holidays in Morocco for 2024 / 2025.
  fr: Feries.ma a dressÃ© le calendrier complet des jours fÃ©riÃ©s au Maroc pour 2024 / 2025.
slogan:
  ar: Ø§Ù„Ø¹Ø·Ù„ Ø§Ù„Ø±Ø³Ù…ÙŠØ© ÙÙŠ Ø§Ù„Ù…ØºØ±Ø¨ ğŸ‡²ğŸ‡¦
  en: Public holidays in Morocco ğŸ‡²ğŸ‡¦
  fr: Jours fÃ©riÃ©s au Maroc ğŸ‡²ğŸ‡¦
footer:
  ar: ØªÙ… Ø¥Ù†Ø´Ø§Ø¤Ù‡ Ø¨ÙƒÙ„ <i class="bi bi-heart"></i> Ø¨Ø§Ù„Ø¯Ø§Ø±Ø§Ù„Ø¨ÙŠØ¶Ø§Ø¡ØŒ Ø§Ù„Ù…ØºØ±Ø¨
  en: Made with <i class="bi bi-heart"></i> in Casablanca, Morocco
  fr: CrÃ©Ã© avec <i class="bi bi-heart"></i> Ã  Casablanca, Maroc
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.feries.ma" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
locales:
  ar: ar_MA
  en: en_US
  fr: fr_FR

languages: ['ar', 'en', 'fr']
default_language: fr

collections:
  feries:
    output: false

plugins:
  - jekyll-sitemap
  
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
